# Generated by Django 3.2.4 on 2021-06-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0002_alter_ciudadela_num_parques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parroquia',
            name='tipo_parroquia',
            field=models.CharField(choices=[('Urbana', 'urbana '), ('Rural', 'rural')], max_length=30, verbose_name='Ubicación de Parroquia'),
        ),
    ]
