# Generated by Django 3.2.4 on 2021-06-12 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0003_alter_parroquia_tipo_parroquia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio_Ciudadela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Barrio o Ciudadela')),
                ('num_viviendas', models.IntegerField(verbose_name='Número de viviendas')),
                ('num_edificios', models.IntegerField(verbose_name='Número de edificios')),
                ('num_parques', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], verbose_name='Numero de Parques')),
            ],
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='tipo_parroquia',
            field=models.CharField(choices=[('Urbana', 'Urbana '), ('Rural', 'Rural')], max_length=30, verbose_name='Ubicación de Parroquia'),
        ),
        migrations.DeleteModel(
            name='Ciudadela',
        ),
        migrations.AddField(
            model_name='barrio_ciudadela',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Parroquia', to='ordenamiento.parroquia'),
        ),
    ]
